# https://opentdb.com/api_config.php

question_data = {
    "Computers": [
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The first computer bug was formed by faulty wires.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "MacOS is based on Linux.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The open source program Redis is a relational database server.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "AMD created the first consumer 64-bit processor.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The first dual-core CPU was the Intel Pentium D.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "It's not possible to format a write-protected DVD-R Hard Disk.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    "General": [
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Coca-Cola's original colour was green.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The vapor produced by e-cigarettes is actually water.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The sum of all the numbers on a roulette wheel is 666.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "There are 86400 seconds in a day.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The bikini is named after the 'Bikini Atoll', an island where the United States conducted tests on atomic bombs.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The French word for 'glass' is 'glace'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    "Games": [
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Super Mario Bros. was released in 1990.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Ace Attorney trilogy was suppose to end with 'Phoenix Wright: Ace Attorney &minus; Trials and Tribulations' as its final game.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Tony Hawk's Pro Skater was released in 1999.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Team Fortress 2', the 'Bill's Hat' is a reference to the game 'Dota 2'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "TF2: The Heavy's voice actor, Gary Schwartz, voices the Demoman as well ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Super Mario World', the rhino mini-boss, Reznor, is named after the lead singer of the band 'Nine Inch Nails'.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Call Of Duty: World At War', the first appearance of the 'PPSH-41' in 'Zombies' was in the map 'Der Riese'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Hidden in the files for 'Mario Kart Arcade GP' is a picture of the Beslan school hostage crisis.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The game Garry's Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    "History": [
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Assyrian king Sennacherib's destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Brezhnev was the 5th leader of the USSR.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Hundred Years' War was fought for more than a hundred years.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
    "Television": [
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "AMC's 'The Walking Dead', Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The television show Doctor Who first aired in 1963.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In the TV series Red Dwarf, Kryten's full name is Kryten 2X4B-523P.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Like his character in 'Parks and Recreation', Aziz Ansari was born in South Carolina.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Bob Ross was a US Air Force pilot.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Star Trek', Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Klingons once had a period of Democracy in their history, they referred to it as the 'Dark Times'.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Star Trek', Klingons are commonly referred to as 'Black Elves'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In 'Star Trek: The Next Generation', Data is the only android in existence.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ],
}
