import requests


# https://openweathermap.org/current#multi
# https://openweathermap.org/forecast5

API_CURRENT = "https://api.openweathermap.org/data/2.5/weather"  # ?lat={lat}&lon={lon}&appid={API key}
API_5_DAY = "https://api.openweathermap.org/data/2.5/forecast"  # ?lat={lat}&lon={lon}&appid={API key}
API_ONECALL = "https://api.openweathermap.org/data/3.0/onecall"  # ?lat={lat}&lon={lon}&exclude={part}&appid={API key}

SILJAN_LAT = 59.276020
SILJAN_LNG = 9.713000

parameters = {
    "lat": SILJAN_LAT,
    "lon": SILJAN_LNG,
    "appid": "9a5d14153344cab145464232471199f4",
    "lang": "no",
}

response_current = requests.get(url=API_CURRENT, params=parameters)
response_current.raise_for_status()
data_current = response_current.json()

response_5 = requests.get(url=API_5_DAY, params=parameters)
response_5.raise_for_status()
data_5 = response_5.json()

response_onecall = requests.get(url=API_ONECALL, params=parameters)
response_onecall.raise_for_status()
data_onecall = response_onecall.json()

print(data_onecall)

# current_data = {
#     "coord": {"lon": 9.713, "lat": 59.276},
#     "weather": [{"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}],
#     "base": "stations",
#     "main": {
#         "temp": 277.58,
#         "feels_like": 276.59,
#         "temp_min": 276.41,
#         "temp_max": 277.91,
#         "pressure": 1024,
#         "humidity": 54,
#         "sea_level": 1024,
#         "grnd_level": 999,
#     },
#     "visibility": 10000,
#     "wind": {"speed": 1.4, "deg": 285, "gust": 2.02},
#     "clouds": {"all": 0},
#     "dt": 1696750973,
#     "sys": {
#         "type": 2,
#         "id": 2033462,
#         "country": "NO",
#         "sunrise": 1696743665,
#         "sunset": 1696782976,
#     },
#     "timezone": 7200,
#     "id": 3139676,
#     "name": "Siljan",
#     "cod": 200,
# }


# data_5 = {
#     "cod": "200",
#     "message": 0,
#     "cnt": 40,
#     "list": [
#         {
#             "dt": 1696755600,
#             "main": {
#                 "temp": 278.67,
#                 "feels_like": 278.67,
#                 "temp_min": 278.67,
#                 "temp_max": 280.12,
#                 "pressure": 1024,
#                 "sea_level": 1024,
#                 "grnd_level": 1000,
#                 "humidity": 47,
#                 "temp_kf": -1.45,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 1.21, "deg": 266, "gust": 1.79},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-08 09:00:00",
#         },
#         {
#             "dt": 1696766400,
#             "main": {
#                 "temp": 280.07,
#                 "feels_like": 278.53,
#                 "temp_min": 280.07,
#                 "temp_max": 282.88,
#                 "pressure": 1024,
#                 "sea_level": 1024,
#                 "grnd_level": 999,
#                 "humidity": 43,
#                 "temp_kf": -2.81,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 3},
#             "wind": {"speed": 2.25, "deg": 220, "gust": 4.51},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-08 12:00:00",
#         },
#         {
#             "dt": 1696777200,
#             "main": {
#                 "temp": 280.5,
#                 "feels_like": 278.72,
#                 "temp_min": 280.5,
#                 "temp_max": 281.42,
#                 "pressure": 1022,
#                 "sea_level": 1022,
#                 "grnd_level": 997,
#                 "humidity": 48,
#                 "temp_kf": -0.92,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03d",
#                 }
#             ],
#             "clouds": {"all": 40},
#             "wind": {"speed": 2.65, "deg": 194, "gust": 6.41},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-08 15:00:00",
#         },
#         {
#             "dt": 1696788000,
#             "main": {
#                 "temp": 278.09,
#                 "feels_like": 278.09,
#                 "temp_min": 278.09,
#                 "temp_max": 278.09,
#                 "pressure": 1020,
#                 "sea_level": 1020,
#                 "grnd_level": 995,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04n",
#                 }
#             ],
#             "clouds": {"all": 80},
#             "wind": {"speed": 0.6, "deg": 191, "gust": 0.73},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-08 18:00:00",
#         },
#         {
#             "dt": 1696798800,
#             "main": {
#                 "temp": 277.65,
#                 "feels_like": 276.53,
#                 "temp_min": 277.65,
#                 "temp_max": 277.65,
#                 "pressure": 1018,
#                 "sea_level": 1018,
#                 "grnd_level": 994,
#                 "humidity": 77,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 1.5, "deg": 350, "gust": 1.35},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-08 21:00:00",
#         },
#         {
#             "dt": 1696809600,
#             "main": {
#                 "temp": 275.4,
#                 "feels_like": 273.24,
#                 "temp_min": 275.4,
#                 "temp_max": 275.4,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 992,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 98},
#             "wind": {"speed": 2.07, "deg": 359, "gust": 2.59},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-09 00:00:00",
#         },
#         {
#             "dt": 1696820400,
#             "main": {
#                 "temp": 274.1,
#                 "feels_like": 271.51,
#                 "temp_min": 274.1,
#                 "temp_max": 274.1,
#                 "pressure": 1016,
#                 "sea_level": 1016,
#                 "grnd_level": 991,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03n",
#                 }
#             ],
#             "clouds": {"all": 47},
#             "wind": {"speed": 2.25, "deg": 349, "gust": 3.57},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-09 03:00:00",
#         },
#         {
#             "dt": 1696831200,
#             "main": {
#                 "temp": 273.7,
#                 "feels_like": 271.26,
#                 "temp_min": 273.7,
#                 "temp_max": 273.7,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 992,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 801,
#                     "main": "Clouds",
#                     "description": "enkelte skyer",
#                     "icon": "02d",
#                 }
#             ],
#             "clouds": {"all": 24},
#             "wind": {"speed": 2.06, "deg": 350, "gust": 2.34},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-09 06:00:00",
#         },
#         {
#             "dt": 1696842000,
#             "main": {
#                 "temp": 279.91,
#                 "feels_like": 279.91,
#                 "temp_min": 279.91,
#                 "temp_max": 279.91,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 993,
#                 "humidity": 49,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 5},
#             "wind": {"speed": 0.66, "deg": 314, "gust": 0.98},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-09 09:00:00",
#         },
#         {
#             "dt": 1696852800,
#             "main": {
#                 "temp": 280.62,
#                 "feels_like": 280.62,
#                 "temp_min": 280.62,
#                 "temp_max": 280.62,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 992,
#                 "humidity": 47,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04d",
#                 }
#             ],
#             "clouds": {"all": 52},
#             "wind": {"speed": 0.88, "deg": 207, "gust": 1.15},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-09 12:00:00",
#         },
#         {
#             "dt": 1696863600,
#             "main": {
#                 "temp": 280.32,
#                 "feels_like": 280.32,
#                 "temp_min": 280.32,
#                 "temp_max": 280.32,
#                 "pressure": 1016,
#                 "sea_level": 1016,
#                 "grnd_level": 992,
#                 "humidity": 56,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04d"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 1.1, "deg": 217, "gust": 2.46},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-09 15:00:00",
#         },
#         {
#             "dt": 1696874400,
#             "main": {
#                 "temp": 276.53,
#                 "feels_like": 276.53,
#                 "temp_min": 276.53,
#                 "temp_max": 276.53,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 992,
#                 "humidity": 72,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 0.63, "deg": 6, "gust": 0.55},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-09 18:00:00",
#         },
#         {
#             "dt": 1696885200,
#             "main": {
#                 "temp": 276.02,
#                 "feels_like": 276.02,
#                 "temp_min": 276.02,
#                 "temp_max": 276.02,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 993,
#                 "humidity": 72,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 0.93, "deg": 349, "gust": 0.9},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-09 21:00:00",
#         },
#         {
#             "dt": 1696896000,
#             "main": {
#                 "temp": 275.21,
#                 "feels_like": 275.21,
#                 "temp_min": 275.21,
#                 "temp_max": 275.21,
#                 "pressure": 1017,
#                 "sea_level": 1017,
#                 "grnd_level": 992,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04n",
#                 }
#             ],
#             "clouds": {"all": 61},
#             "wind": {"speed": 1.14, "deg": 320, "gust": 1.13},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-10 00:00:00",
#         },
#         {
#             "dt": 1696906800,
#             "main": {
#                 "temp": 274.6,
#                 "feels_like": 274.6,
#                 "temp_min": 274.6,
#                 "temp_max": 274.6,
#                 "pressure": 1015,
#                 "sea_level": 1015,
#                 "grnd_level": 990,
#                 "humidity": 78,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01n"}
#             ],
#             "clouds": {"all": 7},
#             "wind": {"speed": 0.94, "deg": 299, "gust": 0.94},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-10 03:00:00",
#         },
#         {
#             "dt": 1696917600,
#             "main": {
#                 "temp": 274.08,
#                 "feels_like": 274.08,
#                 "temp_min": 274.08,
#                 "temp_max": 274.08,
#                 "pressure": 1014,
#                 "sea_level": 1014,
#                 "grnd_level": 989,
#                 "humidity": 79,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 8},
#             "wind": {"speed": 1.06, "deg": 287, "gust": 1.04},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-10 06:00:00",
#         },
#         {
#             "dt": 1696928400,
#             "main": {
#                 "temp": 279.41,
#                 "feels_like": 279.41,
#                 "temp_min": 279.41,
#                 "temp_max": 279.41,
#                 "pressure": 1012,
#                 "sea_level": 1012,
#                 "grnd_level": 987,
#                 "humidity": 55,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03d",
#                 }
#             ],
#             "clouds": {"all": 31},
#             "wind": {"speed": 0.94, "deg": 231, "gust": 1.56},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-10 09:00:00",
#         },
#         {
#             "dt": 1696939200,
#             "main": {
#                 "temp": 281.74,
#                 "feels_like": 280.67,
#                 "temp_min": 281.74,
#                 "temp_max": 281.74,
#                 "pressure": 1009,
#                 "sea_level": 1009,
#                 "grnd_level": 985,
#                 "humidity": 50,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03d",
#                 }
#             ],
#             "clouds": {"all": 50},
#             "wind": {"speed": 2.03, "deg": 231, "gust": 4.99},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-10 12:00:00",
#         },
#         {
#             "dt": 1696950000,
#             "main": {
#                 "temp": 282.27,
#                 "feels_like": 281.12,
#                 "temp_min": 282.27,
#                 "temp_max": 282.27,
#                 "pressure": 1004,
#                 "sea_level": 1004,
#                 "grnd_level": 980,
#                 "humidity": 93,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10d"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 2.24, "deg": 198, "gust": 11.07},
#             "visibility": 10000,
#             "pop": 0.21,
#             "rain": {"3h": 0.18},
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-10 15:00:00",
#         },
#         {
#             "dt": 1696960800,
#             "main": {
#                 "temp": 285.51,
#                 "feels_like": 285.36,
#                 "temp_min": 285.51,
#                 "temp_max": 285.51,
#                 "pressure": 997,
#                 "sea_level": 997,
#                 "grnd_level": 973,
#                 "humidity": 98,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 5.89, "deg": 202, "gust": 15.38},
#             "visibility": 149,
#             "pop": 0.82,
#             "rain": {"3h": 1.3},
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-10 18:00:00",
#         },
#         {
#             "dt": 1696971600,
#             "main": {
#                 "temp": 286.87,
#                 "feels_like": 286.49,
#                 "temp_min": 286.87,
#                 "temp_max": 286.87,
#                 "pressure": 993,
#                 "sea_level": 993,
#                 "grnd_level": 970,
#                 "humidity": 84,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 7.42, "deg": 233, "gust": 16.76},
#             "visibility": 10000,
#             "pop": 0.52,
#             "rain": {"3h": 0.39},
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-10 21:00:00",
#         },
#         {
#             "dt": 1696982400,
#             "main": {
#                 "temp": 285.98,
#                 "feels_like": 285.3,
#                 "temp_min": 285.98,
#                 "temp_max": 285.98,
#                 "pressure": 993,
#                 "sea_level": 993,
#                 "grnd_level": 970,
#                 "humidity": 76,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 100},
#             "wind": {"speed": 7.13, "deg": 247, "gust": 15.98},
#             "visibility": 10000,
#             "pop": 0.21,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-11 00:00:00",
#         },
#         {
#             "dt": 1696993200,
#             "main": {
#                 "temp": 280.4,
#                 "feels_like": 277.21,
#                 "temp_min": 280.4,
#                 "temp_max": 280.4,
#                 "pressure": 994,
#                 "sea_level": 994,
#                 "grnd_level": 970,
#                 "humidity": 68,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04n"}
#             ],
#             "clouds": {"all": 85},
#             "wind": {"speed": 5.22, "deg": 242, "gust": 11.73},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-11 03:00:00",
#         },
#         {
#             "dt": 1697004000,
#             "main": {
#                 "temp": 279.42,
#                 "feels_like": 276.25,
#                 "temp_min": 279.42,
#                 "temp_max": 279.42,
#                 "pressure": 995,
#                 "sea_level": 995,
#                 "grnd_level": 971,
#                 "humidity": 69,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04d",
#                 }
#             ],
#             "clouds": {"all": 71},
#             "wind": {"speed": 4.63, "deg": 238, "gust": 11.44},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-11 06:00:00",
#         },
#         {
#             "dt": 1697014800,
#             "main": {
#                 "temp": 281.7,
#                 "feels_like": 278.38,
#                 "temp_min": 281.7,
#                 "temp_max": 281.7,
#                 "pressure": 993,
#                 "sea_level": 993,
#                 "grnd_level": 970,
#                 "humidity": 66,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 804, "main": "Clouds", "description": "overskyet", "icon": "04d"}
#             ],
#             "clouds": {"all": 95},
#             "wind": {"speed": 6.51, "deg": 235, "gust": 13.49},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-11 09:00:00",
#         },
#         {
#             "dt": 1697025600,
#             "main": {
#                 "temp": 282.92,
#                 "feels_like": 279.86,
#                 "temp_min": 282.92,
#                 "temp_max": 282.92,
#                 "pressure": 990,
#                 "sea_level": 990,
#                 "grnd_level": 967,
#                 "humidity": 62,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10d"}
#             ],
#             "clouds": {"all": 56},
#             "wind": {"speed": 6.77, "deg": 247, "gust": 15.99},
#             "visibility": 10000,
#             "pop": 0.2,
#             "rain": {"3h": 0.12},
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-11 12:00:00",
#         },
#         {
#             "dt": 1697036400,
#             "main": {
#                 "temp": 280.87,
#                 "feels_like": 276.75,
#                 "temp_min": 280.87,
#                 "temp_max": 280.87,
#                 "pressure": 988,
#                 "sea_level": 988,
#                 "grnd_level": 964,
#                 "humidity": 71,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03d",
#                 }
#             ],
#             "clouds": {"all": 37},
#             "wind": {"speed": 8.4, "deg": 242, "gust": 20.16},
#             "visibility": 10000,
#             "pop": 0.01,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-11 15:00:00",
#         },
#         {
#             "dt": 1697047200,
#             "main": {
#                 "temp": 280.42,
#                 "feels_like": 276.07,
#                 "temp_min": 280.42,
#                 "temp_max": 280.42,
#                 "pressure": 985,
#                 "sea_level": 985,
#                 "grnd_level": 962,
#                 "humidity": 78,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10n"}
#             ],
#             "clouds": {"all": 68},
#             "wind": {"speed": 8.71, "deg": 249, "gust": 19.35},
#             "visibility": 10000,
#             "pop": 0.23,
#             "rain": {"3h": 0.18},
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-11 18:00:00",
#         },
#         {
#             "dt": 1697058000,
#             "main": {
#                 "temp": 279.71,
#                 "feels_like": 275.55,
#                 "temp_min": 279.71,
#                 "temp_max": 279.71,
#                 "pressure": 986,
#                 "sea_level": 986,
#                 "grnd_level": 962,
#                 "humidity": 68,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 500, "main": "Rain", "description": "lett regn", "icon": "10n"}
#             ],
#             "clouds": {"all": 77},
#             "wind": {"speed": 7.37, "deg": 266, "gust": 17.74},
#             "visibility": 10000,
#             "pop": 0.4,
#             "rain": {"3h": 0.13},
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-11 21:00:00",
#         },
#         {
#             "dt": 1697068800,
#             "main": {
#                 "temp": 280.02,
#                 "feels_like": 275.96,
#                 "temp_min": 280.02,
#                 "temp_max": 280.02,
#                 "pressure": 987,
#                 "sea_level": 987,
#                 "grnd_level": 963,
#                 "humidity": 60,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04n",
#                 }
#             ],
#             "clouds": {"all": 59},
#             "wind": {"speed": 7.32, "deg": 270, "gust": 17.76},
#             "visibility": 10000,
#             "pop": 0.14,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-12 00:00:00",
#         },
#         {
#             "dt": 1697079600,
#             "main": {
#                 "temp": 279.78,
#                 "feels_like": 275.93,
#                 "temp_min": 279.78,
#                 "temp_max": 279.78,
#                 "pressure": 988,
#                 "sea_level": 988,
#                 "grnd_level": 965,
#                 "humidity": 64,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01n"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 6.51, "deg": 273, "gust": 15.41},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-12 03:00:00",
#         },
#         {
#             "dt": 1697090400,
#             "main": {
#                 "temp": 280.62,
#                 "feels_like": 276.97,
#                 "temp_min": 280.62,
#                 "temp_max": 280.62,
#                 "pressure": 992,
#                 "sea_level": 992,
#                 "grnd_level": 968,
#                 "humidity": 56,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 6.59, "deg": 303, "gust": 17.6},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-12 06:00:00",
#         },
#         {
#             "dt": 1697101200,
#             "main": {
#                 "temp": 283.73,
#                 "feels_like": 282.04,
#                 "temp_min": 283.73,
#                 "temp_max": 283.73,
#                 "pressure": 998,
#                 "sea_level": 998,
#                 "grnd_level": 975,
#                 "humidity": 46,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 4.41, "deg": 310, "gust": 10.63},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-12 09:00:00",
#         },
#         {
#             "dt": 1697112000,
#             "main": {
#                 "temp": 285.94,
#                 "feels_like": 284.32,
#                 "temp_min": 285.94,
#                 "temp_max": 285.94,
#                 "pressure": 1002,
#                 "sea_level": 1002,
#                 "grnd_level": 978,
#                 "humidity": 40,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 4.33, "deg": 310, "gust": 9.78},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-12 12:00:00",
#         },
#         {
#             "dt": 1697122800,
#             "main": {
#                 "temp": 283.6,
#                 "feels_like": 281.9,
#                 "temp_min": 283.6,
#                 "temp_max": 283.6,
#                 "pressure": 1006,
#                 "sea_level": 1006,
#                 "grnd_level": 982,
#                 "humidity": 46,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {"id": 800, "main": "Clear", "description": "klart", "icon": "01d"}
#             ],
#             "clouds": {"all": 0},
#             "wind": {"speed": 5.11, "deg": 298, "gust": 11.08},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-12 15:00:00",
#         },
#         {
#             "dt": 1697133600,
#             "main": {
#                 "temp": 280.21,
#                 "feels_like": 277.67,
#                 "temp_min": 280.21,
#                 "temp_max": 280.21,
#                 "pressure": 1009,
#                 "sea_level": 1009,
#                 "grnd_level": 985,
#                 "humidity": 54,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 801,
#                     "main": "Clouds",
#                     "description": "enkelte skyer",
#                     "icon": "02n",
#                 }
#             ],
#             "clouds": {"all": 23},
#             "wind": {"speed": 3.75, "deg": 307, "gust": 12.01},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-12 18:00:00",
#         },
#         {
#             "dt": 1697144400,
#             "main": {
#                 "temp": 277.44,
#                 "feels_like": 275.73,
#                 "temp_min": 277.44,
#                 "temp_max": 277.44,
#                 "pressure": 1011,
#                 "sea_level": 1011,
#                 "grnd_level": 987,
#                 "humidity": 69,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 803,
#                     "main": "Clouds",
#                     "description": "spredt skydekke",
#                     "icon": "04n",
#                 }
#             ],
#             "clouds": {"all": 73},
#             "wind": {"speed": 1.96, "deg": 312, "gust": 2.89},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-12 21:00:00",
#         },
#         {
#             "dt": 1697155200,
#             "main": {
#                 "temp": 276.05,
#                 "feels_like": 274.2,
#                 "temp_min": 276.05,
#                 "temp_max": 276.05,
#                 "pressure": 1013,
#                 "sea_level": 1013,
#                 "grnd_level": 988,
#                 "humidity": 72,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03n",
#                 }
#             ],
#             "clouds": {"all": 49},
#             "wind": {"speed": 1.89, "deg": 312, "gust": 1.87},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-13 00:00:00",
#         },
#         {
#             "dt": 1697166000,
#             "main": {
#                 "temp": 275.45,
#                 "feels_like": 273.74,
#                 "temp_min": 275.45,
#                 "temp_max": 275.45,
#                 "pressure": 1013,
#                 "sea_level": 1013,
#                 "grnd_level": 989,
#                 "humidity": 72,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 801,
#                     "main": "Clouds",
#                     "description": "enkelte skyer",
#                     "icon": "02n",
#                 }
#             ],
#             "clouds": {"all": 23},
#             "wind": {"speed": 1.7, "deg": 308, "gust": 1.59},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "n"},
#             "dt_txt": "2023-10-13 03:00:00",
#         },
#         {
#             "dt": 1697176800,
#             "main": {
#                 "temp": 275.09,
#                 "feels_like": 275.09,
#                 "temp_min": 275.09,
#                 "temp_max": 275.09,
#                 "pressure": 1013,
#                 "sea_level": 1013,
#                 "grnd_level": 989,
#                 "humidity": 73,
#                 "temp_kf": 0,
#             },
#             "weather": [
#                 {
#                     "id": 802,
#                     "main": "Clouds",
#                     "description": "spredte skyer",
#                     "icon": "03d",
#                 }
#             ],
#             "clouds": {"all": 48},
#             "wind": {"speed": 1.25, "deg": 319, "gust": 1.24},
#             "visibility": 10000,
#             "pop": 0,
#             "sys": {"pod": "d"},
#             "dt_txt": "2023-10-13 06:00:00",
#         },
#     ],
#     "city": {
#         "id": 3139676,
#         "name": "Siljan",
#         "coord": {"lat": 59.276, "lon": 9.713},
#         "country": "NO",
#         "population": 1000,
#         "timezone": 7200,
#         "sunrise": 1696743665,
#         "sunset": 1696782976,
#     },
# }
